# Generated by Django 5.2.4 on 2025-08-07 21:04

import apps.movies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, help_text='The director of the movie', max_length=255, null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_cast',
            field=models.JSONField(blank=True, default=list, help_text='List of main cast members', null=True, validators=[apps.movies.models.validate_json_array], verbose_name='Main Cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='omdb_rating',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The OMDB rating of the movie', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='OMDB Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='our_rating',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='User-generated average rating of the movie', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Our Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_rating',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The TMDB rating of the movie', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='TMDB Rating'),
        ),
    ]
