# Generated by Django 5.2.4 on 2025-08-07 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_director_alter_movie_main_cast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity_score',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='The popularity score of the movie', max_digits=10, verbose_name='Popularity'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_rating',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The TMDB rating of the movie', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='TMDB Rating'),
        ),
    ]
