# Generated by Django 5.2.4 on 2025-08-08 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_popularity_score_alter_movie_tmdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='omdb_rating',
            field=models.FloatField(blank=True, help_text='The OMDB rating of the movie', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='OMDB Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='our_rating',
            field=models.FloatField(blank=True, help_text='User-generated average rating of the movie', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Our Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='The popularity score of the movie based on TMDB metrics', verbose_name='Popularity Score'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_rating',
            field=models.FloatField(blank=True, help_text='The TMDB rating of the movie', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='TMDB Rating'),
        ),
    ]
