services:
  - type: web
    name: movie-recommendation-backend
    env: python
    region: oregon # or your preferred region
    plan: free 
    
    # Build configuration
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    
    # Start command - use your existing entrypoint.sh
    startCommand: "./entrypoint.sh"
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11  # adjust to your Python version
      - key: DATABASE_URL
        fromDatabase:
          name: movie-recommendation-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: movie_recommendation_backend.settings  # adjust to your settings module
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: POSTGRES_DB
        value: Movie_Recommendation
      - key: POSTGRES_USER
        value: movie_user
    
    # Health check (optional)
    healthCheckPath: /
    
    # Auto-deploy from git
    autoDeploy: true

# Database configuration
databases:
  - name: movie-recommendation-db
    databaseName: $POSTGRES_DB
    user: $POSTGRES_USER
    region: oregon  # same region as your web service
    plan: free  #