# Generated by Django 5.2.4 on 2025-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotifications',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inappnotifications',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
