# Generated by Django 5.2.4 on 2025-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_algorithm_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='algorithm_preference',
            field=models.CharField(blank=True, help_text='Preferred recommendation algorithm.', max_length=50, null=True),
        ),
    ]
